### ISSUE TITLE
Problem installing Archiconda3

### ISSUE THREAD

**Issue by iOrevir** [Maximilian-Pichler/BDPi#1]
While running the ansible playbook I had a problem with Archiconda3. 

```batch
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: /home/ubuntu/archiconda3/bin/conda.
fatal: [10.48.1.160]: FAILED! => {"changed": false, "msg": "The command was not found or was not executable: /home/ubuntu/archiconda3/bin/conda."}
```

I solve it connecting to the RPi and deleting the Archiconda3 folder. Then, I re-ran the playbook.

Hope this helps!

**Comment by Maximilian-Pichler** [comment]
Thx for the feedback @iOrevir!

I think i know what the issues might be.
Did you, by chance, interrupt a previous run of the script? If that is the case, it would explain the behaviour:

When installing archiconda, the playbook first checks if there is already a folder called archiconda.
if the folder is present, it assumes that archiconda is installed.

Anyway, I will enhance the check, so that it looks for some binary, like conda. 
The previous method was not optimal.

**Comment by iOrevir** [comment]
Thanks for the feedback @Maximilian-Pichler 

Indeed! I interrupted the installation after 30 min of not seeing any change in the process. Completely my fault.

Keep up the great work!

**Comment by Maximilian-Pichler** [comment]
Then we have found the issue.
I updated the check, so in the future, this should not happen that easily.

Thank's again for the feedback, I'll close this issue for now
